### ISSUE TITLE
[bug] Syntax error in role_mappings.tfvars.j2

### ISSUE THREAD

**Issue by shaneholder** [Azure/caf-terraform-landingzones#305] opened 2022-01-31 00:35 UTC
When running through the examples on the 2201 branch the rover ignite command generates the role_mappings.tfvars file with a syntax error at the end of the file.  I believe it is due to a missing closing brace due to the endif on line [185](https://github.com/Azure/caf-terraform-landingzones/blob/5a9f9ac59b5a8c349dc79d5c8703951f87fa6518/templates/platform/level0/launchpad/role_mappings.tfvars.j2#L185)

I believe swapping line 184 and 185 will fix the template.

**Comment by arnaudlh** [comment] 2022-04-01 00:40
Thanks for your submission @shaneholder, I will close as resolved in #332 and merged please reopen if you feel the problem is not resolved! Thanks.

**Closed by arnaudlh** 2022-04-01 00:40 UTC
Labels: bug
