### ISSUE TITLE
rover run plan issue

### ISSUE THREAD

**Issue by 20FS21** [Azure/caf-terraform-landingzones#352] opened 2022-04-07 00:04 UTC
Hello team,
I started to deploy CAF Azure for my first time. i follow the guide that find here:
https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/platform/single%20reuse/elsz-single-reuse
When i run onther configuration-->level0-->launchpad-->readme.md command:
rover \
  -lz /tf/caf/landingzones/caf_launchpad \
  -var-folder /tf/caf/configuration/level0/launchpad \
  -tfstate_subscription_id xxxx \
  -target_subscription xxxx \
  -tfstate caf_launchpad.tfstate \
  -launchpad \
  -env contoso \
  -level level0 \
  -p ${TF_DATA_DIR}/caf_launchpad.tfstate.tfplan \
  -a plan

I find this error:

@calling terraform_plan -- azurerm
╷
│ Error: reading Management Group "xxxxx": managementgroups.Client#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="'/providers/Microsoft.Management/managementGroups/xxxxxxxxx' not found"
│ 
│   with module.launchpad.data.azurerm_management_group.level["root"],
│   on /home/vscode/.terraform.cache/launchpad/contoso/modules/launchpad/roles.tf line 41, in data "azurerm_management_group" "level":
│   41: data "azurerm_management_group" "level" {
│ 
╵
Terraform plan return code: 1
Error on or near line 391: Error running terraform plan; exiting with status 1

could you help me to fix this. for your information i use visual studio code for configure this env.
Thanks a lot.

**Comment by SipkeW** [comment] 2022-04-08 10:25
i fixed this quick and dirty, not as intended, but in my tenant, the managemtn groups weren't activated, so logging in to azure, opneing management groups, and activating, or starting or something, after that it ran fine.

**Comment by simonepegperego** [comment] 2022-04-08 21:03
@20FS21 I would check 2 things:
- be sure you properly fulfill the fields required by the '/tf/caf/landingzones/templates/platform/deploy_platform.sh' 
- from the Azure Active Directory portal click on the Properties blade and check the option "Access Management fo Azure resources" for the account you're using to deploy is set to YES.
![image](https://user-images.githubusercontent.com/100087399/162529540-151ef0aa-09b7-4da3-913d-6572c5d65cfe.png)

**Comment by LaurentLesle** [comment] 2022-04-13 06:46
Closed as answered by @simonepegperego

**Closed by LaurentLesle** 2022-04-13 06:46 UTC
Labels: enhancement

**Comment by 20FS21** [comment] 2022-04-13 07:03
Thanks a lot
