### ISSUE TITLE
Kustomization path is outdated

### ISSUE THREAD

**Issue by svadali2** [Azure/caf-terraform-landingzones#234] opened 2021-08-03 08:51 UTC
**Describe the bug**
Kustomization path is outdated. 

**To Reproduce**
1. Go to https://github.com/Azure/caf-terraform-landingzones/blob/master/caf_solution/add-ons/aks-secure-baseline/kustomization.yaml
3. Open the link in line 5. It will be broken.

**Expected behavior**
The link should be updated as per the new project structure in starter branch of caf-terraform-starter project. It should point to [https://raw.githubusercontent.com/Azure/caf-terraform-landingzones-starter/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/cluster-baseline-settings/flux/flux.yaml](https://raw.githubusercontent.com/Azure/caf-terraform-landingzones-starter/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/cluster-baseline-settings/flux/flux.yaml)

**Configuration (please complete the following information):**
 - OS and version: [NA]
 - Version of the rover[NA]
 - Version of the landing zone[NA]

**Additional context**
None

**Comment by arnaudlh** [comment] 2021-08-25 11:16
Merged into 2108.0. Let us know if the issue is still happening!
thanks

**Closed by arnaudlh** 2021-08-25 11:16 UTC
Labels: bug
